CREATE TABLE Stations (
	Id SERIAL,
	Name VARCHAR(250) NULL,
	Street VARCHAR(100) NULL,
	Number VARCHAR(20) NULL,
	Neighborhood VARCHAR(50) NULL,
	City VARCHAR(20) NULL,
	State VARCHAR(20) NULL,
	Lat VARCHAR(20) NULL,
	Lng VARCHAR(20) NULL
);