CREATE TABLE `Stations` (
	`Id` int(10) UNSIGNED NULL DEFAULT NULL,
	`Name` VARCHAR(250) NULL DEFAULT NULL,
	`Street` VARCHAR(100) NULL DEFAULT NULL,
	`Number` VARCHAR(20) NULL DEFAULT NULL,
	`Neighborhood` VARCHAR(50) NULL DEFAULT NULL,
	`City` VARCHAR(20) NULL DEFAULT NULL,
	`State` VARCHAR(20) NULL DEFAULT NULL,
	`Lat` VARCHAR(20) NULL DEFAULT NULL,
	`Lng` VARCHAR(20) NULL DEFAULT NULL
)
ENGINE=InnoDB
;