# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  # gnv-mysql-data:
  #   driver: local
  # Postgres Data
    gnv-postgres-data:
      driver: local

services:
  ## MySQL (5.7)
  # mysql:
  #   image: ambientum/mysql:5.7
  #   container_name: gnv-mysql
  #   volumes:
  #     - gnv-mysql-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=gnv
  #     - MYSQL_DATABASE=gnv
  #     - MYSQL_USER=gnv
  #     - MYSQL_PASSWORD=gnv
  postgres:
    image: postgres:10.3-alpine
    restart: always
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_PASSWORD: gnv-no-app
      POSTGRES_USER: gnv-no-app
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - gnv-postgres-data:/var/lib/postgresql/data